#!/bin/bash

if [ $# -ne 4 ]
then
	echo "Usage $0 <input directory> <output directory> <input.BAM> <output prefix>"
	exit 2
fi 



indir=$1
outdir=$2
inputBam=$3
output=$4

sortedsam=$output.sorted.bam

sambamba sort -o $outdir/$sortedsam $indir/$inputBam 

markdupsam=$output.sorted.marked.bam

sambamba markdup $outdir/$sortedsam $outdir/$markdupsam

sambamba flagstat $outdir/$markdupsam
